spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oop
    username: fedaoop
    password: 2006
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update